# Generated by Django 5.2 on 2025-04-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='quantity_unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('servings', 'Servings'), ('grams', 'Grams'), ('kg', 'Kilograms'), ('liters', 'Liters'), ('ml', 'Milliliters')], default='pcs', max_length=20),
        ),
    ]
