# Generated by Django 5.2 on 2025-04-25 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_fooditem_quantity_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='donation_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_items', to='track.donationcenter'),
        ),
    ]
