# Generated by Django 5.2 on 2025-04-29 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_fooditem_donation_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='donation_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='track.donationcenter'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='is_surplus',
            field=models.BooleanField(default=False),
        ),
    ]
